import { Report } from "@shared/schema";
import PDFKit from "pdfkit";
import { format } from "date-fns";
// Need change intypescript

export class ReportGenerator {
  async generatePDF(report: Report): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFKit();
        const chunks: Buffer[] = [];

        doc.on('data', (chunk) => chunks.push(chunk));
        doc.on('end', () => resolve(Buffer.concat(chunks)));

        // Header with logo and title
        doc.fontSize(24).fillColor('#2563eb').text('Vehicle Damage Report', 50, 50);
        doc.fontSize(12).fillColor('#6b7280').text('Professional Insurance Documentation', 50, 80);

        // Reference number box
        doc.rect(400, 40, 150, 60).fillAndStroke('#3b82f6', '#1d4ed8');
        doc.fontSize(8).fillColor('#ffffff').text('Reference Number', 410, 50);
        doc.fontSize(14).fillColor('#ffffff').text(report.referenceNumber, 410, 65);

        // Report metadata
        const currentY = 130;
        doc.fontSize(10).fillColor('#374151');
        doc.text(`Report Generated: ${format(new Date(), 'MMMM dd, yyyy \'at\' h:mm a')}`, 50, currentY);
        doc.text('Status: Submitted', 300, currentY);

        // Vehicle Information Section
        let y = currentY + 40;
        this.addSection(doc, 'Vehicle Information', y);
        y += 30;

        const vehicleInfo = [
          ['License Plate:', report.licensePlate],
          ['Make & Model:', `${report.make} ${report.model}`],
          ['Year:', report.year],
          ['Color:', report.color || 'Not specified'],
          ['VIN:', report.vin || 'Not provided']
        ];

        vehicleInfo.forEach(([label, value], index) => {
          const row = Math.floor(index / 2);
          const col = index % 2;
          const x = col === 0 ? 50 : 300;
          const rowY = y + (row * 25);
          
          doc.fontSize(9).fillColor('#6b7280').text(label, x, rowY);
          doc.fontSize(10).fillColor('#111827').text(value, x, rowY + 12);
        });

        // Incident Details Section
        y += vehicleInfo.length * 15 + 40;
        this.addSection(doc, 'Incident Details', y);
        y += 30;

        const incidentDateTime = report.incidentTime 
          ? `${report.incidentDate} at ${report.incidentTime}`
          : report.incidentDate;

        doc.fontSize(9).fillColor('#6b7280').text('Date & Time:', 50, y);
        doc.fontSize(10).fillColor('#111827').text(incidentDateTime, 50, y + 12);

        if (report.location) {
          doc.fontSize(9).fillColor('#6b7280').text('Location:', 300, y);
          doc.fontSize(10).fillColor('#111827').text(report.location, 300, y + 12);
        }

        y += 40;
        doc.fontSize(9).fillColor('#6b7280').text('Description:', 50, y);
        y += 15;
        
        // Wrap description text
        const descriptionLines = doc.widthOfString(report.description) > 500 
          ? this.wrapText(doc, report.description, 500)
          : [report.description];
        
        descriptionLines.forEach((line, index) => {
          doc.fontSize(10).fillColor('#111827').text(line, 50, y + (index * 15));
        });

        // Photos section
        y += descriptionLines.length * 15 + 40;
        this.addSection(doc, 'Damage Documentation', y);
        y += 30;

        doc.fontSize(10).fillColor('#374151').text(`${report.photoUrls.length} photos attached`, 50, y);
        
        report.photoUrls.forEach((url, index) => {
          y += 20;
          doc.fontSize(9).fillColor('#6b7280').text(`Photo ${index + 1}:`, 50, y);
          doc.fontSize(9).fillColor('#3b82f6').text(url, 120, y);
        });

        // Reporter Information Section
        y += 40;
        this.addSection(doc, 'Reported By', y);
        y += 30;

        const reporterInfo = [
          ['Name:', report.reporterName],
          ['Contact Number:', report.reporterPhone],
          ['Email:', report.reporterEmail]
        ];

        reporterInfo.forEach(([label, value], index) => {
          const row = Math.floor(index / 2);
          const col = index % 2;
          const x = col === 0 ? 50 : 300;
          const rowY = y + (row * 25);
          
          doc.fontSize(9).fillColor('#6b7280').text(label, x, rowY);
          doc.fontSize(10).fillColor('#111827').text(value, x, rowY + 12);
        });

        // Footer
        y += 100;
        doc.rect(50, y, 500, 1).fill('#e5e7eb');
        y += 15;
        
        doc.fontSize(8).fillColor('#6b7280');
        doc.text('🛡️ This report is digitally verified and timestamped', 50, y);
        doc.text('Generated by VehicleClaim Pro v1.0', 400, y);

        doc.end();
      } catch (error) {
        reject(error);
      }
    });
  }

  private addSection(doc: PDFKit.PDFDocument, title: string, y: number) {
    doc.fontSize(16).fillColor('#1f2937').text(title, 50, y);
    doc.rect(50, y + 20, 500, 1).fill('#e5e7eb');
  }

  private wrapText(doc: PDFKit.PDFDocument, text: string, maxWidth: number): string[] {
    const words = text.split(' ');
    const lines: string[] = [];
    let currentLine = '';

    for (const word of words) {
      const testLine = currentLine ? `${currentLine} ${word}` : word;
      const width = doc.widthOfString(testLine);
      
      if (width > maxWidth && currentLine) {
        lines.push(currentLine);
        currentLine = word;
      } else {
        currentLine = testLine;
      }
    }
    
    if (currentLine) {
      lines.push(currentLine);
    }

    return lines;
  }

  generateHTML(report: Report): string {
    const incidentDateTime = report.incidentTime 
      ? `${report.incidentDate} at ${report.incidentTime}`
      : report.incidentDate;

    return `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vehicle Damage Report - ${report.referenceNumber}</title>
    <style>
        body { font-family: Inter, sans-serif; line-height: 1.6; color: #111827; margin: 0; padding: 20px; }
        .header { background: linear-gradient(to right, #3b82f6, #2563eb); color: white; padding: 2rem; border-radius: 8px; margin-bottom: 2rem; }
        .ref-number { background: rgba(255,255,255,0.1); padding: 1rem; border-radius: 8px; text-align: right; }
        .section { margin-bottom: 2rem; }
        .section-title { font-size: 1.25rem; font-weight: bold; margin-bottom: 1rem; color: #1f2937; }
        .info-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 1rem; }
        .info-item { margin-bottom: 0.5rem; }
        .label { font-size: 0.875rem; color: #6b7280; margin-bottom: 0.25rem; }
        .value { font-weight: 600; }
        .description { background: #f9fafb; padding: 1rem; border-radius: 8px; }
        .footer { border-top: 1px solid #e5e7eb; padding-top: 1rem; margin-top: 2rem; font-size: 0.875rem; color: #6b7280; }
        @media print { body { margin: 0; } }
    </style>
</head>
<body>
    <div class="header">
        <div style="display: flex; justify-content: space-between; align-items: start;">
            <div>
                <h1 style="font-size: 2rem; margin: 0 0 0.5rem 0;">Vehicle Damage Report</h1>
                <p style="color: #bfdbfe; margin: 0;">Professional Insurance Documentation</p>
            </div>
            <div class="ref-number">
                <div style="font-size: 0.75rem; opacity: 0.8;">Reference Number</div>
                <div style="font-size: 1.5rem; font-family: monospace; font-weight: bold;">${report.referenceNumber}</div>
            </div>
        </div>
    </div>

    <div class="section">
        <div class="info-grid">
            <div class="info-item">
                <div class="label">Report Generated</div>
                <div class="value">${format(new Date(), 'MMMM dd, yyyy \'at\' h:mm a')}</div>
            </div>
            <div class="info-item">
                <div class="label">Status</div>
                <div class="value">Submitted</div>
            </div>
        </div>
    </div>

    <div class="section">
        <h3 class="section-title">🚗 Vehicle Information</h3>
        <div class="info-grid">
            <div class="info-item">
                <div class="label">License Plate</div>
                <div class="value">${report.licensePlate}</div>
            </div>
            <div class="info-item">
                <div class="label">Make & Model</div>
                <div class="value">${report.make} ${report.model}</div>
            </div>
            <div class="info-item">
                <div class="label">Year</div>
                <div class="value">${report.year}</div>
            </div>
            <div class="info-item">
                <div class="label">Color</div>
                <div class="value">${report.color || 'Not specified'}</div>
            </div>
            ${report.vin ? `
            <div class="info-item">
                <div class="label">VIN</div>
                <div class="value" style="font-family: monospace;">${report.vin}</div>
            </div>
            ` : ''}
        </div>
    </div>

    <div class="section">
        <h3 class="section-title">⚠️ Incident Details</h3>
        <div class="info-grid">
            <div class="info-item">
                <div class="label">Date & Time</div>
                <div class="value">${incidentDateTime}</div>
            </div>
            ${report.location ? `
            <div class="info-item">
                <div class="label">Location</div>
                <div class="value">${report.location}</div>
            </div>
            ` : ''}
        </div>
        <div class="info-item" style="margin-top: 1rem;">
            <div class="label">Description</div>
            <div class="description">${report.description}</div>
        </div>
    </div>

    <div class="section">
        <h3 class="section-title">📷 Damage Documentation</h3>
        <p>${report.photoUrls.length} photos attached to this report.</p>
        ${report.photoUrls.map((url, index) => `
            <div style="margin-bottom: 0.5rem;">
                <strong>Photo ${index + 1}:</strong> <span style="color: #3b82f6;">${url}</span>
            </div>
        `).join('')}
    </div>

    <div class="section">
        <h3 class="section-title">👤 Reported By</h3>
        <div class="info-grid">
            <div class="info-item">
                <div class="label">Name</div>
                <div class="value">${report.reporterName}</div>
            </div>
            <div class="info-item">
                <div class="label">Contact Number</div>
                <div class="value">${report.reporterPhone}</div>
            </div>
            <div class="info-item">
                <div class="label">Email</div>
                <div class="value">${report.reporterEmail}</div>
            </div>
        </div>
    </div>

    <div class="footer">
        <div style="display: flex; justify-content: space-between;">
            <div>🛡️ This report is digitally verified and timestamped</div>
            <div>Generated by VehicleClaim Pro v1.0</div>
        </div>
    </div>
</body>
</html>
    `;
  }
}
